# Generated by Django 2.0.3 on 2018-03-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=5000)),
                ('senderwallet', models.CharField(max_length=5000)),
                ('receiver', models.CharField(max_length=5000)),
                ('prevblockhash', models.CharField(max_length=5000)),
                ('blockhash', models.CharField(max_length=5000)),
                ('amount', models.IntegerField()),
                ('nonce', models.IntegerField()),
                ('first_timestamp', models.IntegerField()),
                ('saved_timestamp', models.DateTimeField(auto_now_add=True)),
                ('P2PKH', models.CharField(max_length=5000)),
                ('verification', models.BooleanField()),
            ],
        ),
    ]
