# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=5000)),
                ('senderhexdigest', models.CharField(max_length=5000)),
                ('receiver', models.CharField(max_length=5000)),
                ('receiverhexdigest', models.CharField(max_length=5000)),
                ('prevblockhash', models.CharField(max_length=5000)),
                ('blockhash', models.CharField(max_length=5000)),
                ('amount', models.IntegerField()),
                ('nonce', models.IntegerField()),
                ('first_timestamp', models.IntegerField()),
                ('saved_timestamp', models.DateTimeField(auto_now_add=True)),
                ('P2PKH', models.CharField(max_length=5000)),
                ('verification', models.BooleanField()),
            ],
        ),
    ]
